import asyncio
import logging
from typing import Optional

from google.adk import Workflow, Event
from google.adk.runners import Runner
from google.genai import types as genai_types

from core.adk.agents import (
    questionnaire_agent,
    photo_diagnost_agent,
    video_motion_agent,
    technique_expert_agent,
    music_recommend_agent,
    final_synthesis_agent,
)
from core.adk.session import get_session_service, get_memory_service, create_session
from core.adk.tools import question_analyzer_tool

logger = logging.getLogger(__name__)


def _analyze_and_pass(node_input: str) -> Event:
    """Validate questionnaire completeness and pass to the next agent."""
    import re
    checks = {
        "возраст|лет|age": "age",
        "жалоб|complaint|боль|pain": "complaints",
        "лока|locat|где|where": "location",
        "тип|type|характер|nature": "pain_type",
        "длитель|duration|как долго": "duration",
        "хронич|chronic|заболев": "chronic",
        "противопоказан|contraind": "contraindications",
    }
    found = []
    for pattern, field in checks.items():
        if re.search(pattern, node_input, re.IGNORECASE):
            found.append(field)
    info = f"[META] Questionnaire fields detected: {', '.join(found) or 'none'}"
    return Event(output=f"{info}\n\n{node_input}")


def _accumulate_context(node_input: str) -> Event:
    """Format accumulated context for the next specialist."""
    return Event(
        output=f"[CONTEXT] The following is the full consultation data so far.\n\n{node_input}"
    )


def _extract_music_recommendation(node_input: str) -> Event:
    """Parse music recommendation from technique expert output."""
    return Event(
        output=f"[MUSIC_REQ] Based on the assessment above, recommend appropriate music.\n\n{node_input}"
    )


def _finalize_report(node_input: str) -> Event:
    """Format the final consultation report."""
    return Event(
        message=f"📋 **Massage Consultation Complete**\n\n{node_input}\n\n"
        f"_Generated by AI Prophet ADK Workflow_"
    )


_analyze_node = _analyze_and_pass
_accumulate_node = _accumulate_context
_music_extract_node = _extract_music_recommendation
_finalize_node = _finalize_report


massage_workflow = Workflow(
    name="massage_consultation_workflow",
    edges=[
        ("START", questionnaire_agent, _analyze_node, photo_diagnost_agent),
        (photo_diagnost_agent, video_motion_agent),
        (video_motion_agent, _accumulate_node, technique_expert_agent),
        (technique_expert_agent, _music_extract_node, music_recommend_agent),
        (music_recommend_agent, _finalize_node, final_synthesis_agent),
    ],
)


_session_service = get_session_service()
_memory_service = get_memory_service()

_runner = Runner(
    app_name="ai_prophet",
    agent=massage_workflow,
    session_service=_session_service,
    memory_service=_memory_service,
    auto_create_session=True,
)


def create_massage_workflow() -> Workflow:
    """Get the massage consultation workflow instance."""
    return massage_workflow


async def run_massage_consultation(
    chat_id: int,
    user_message: str,
) -> list[dict]:
    """Run a full massage consultation workflow.

    Args:
        chat_id: User/chat identifier
        user_message: Initial user message describing the complaint

    Returns:
        List of event dicts from the workflow execution
    """
    session_id = f"{chat_id}_massage_consultation"

    session = _session_service.create_session_sync(
        app_name="ai_prophet",
        user_id=str(chat_id),
        session_id=session_id,
    )

    content = genai_types.Content(
        role="user",
        parts=[genai_types.Part(text=user_message)],
    )

    events = []
    for event in _runner.run(
        user_id=str(chat_id),
        session_id=session_id,
        new_message=content,
    ):
        if event.content and event.content.parts:
            text = "".join(
                p.text for p in event.content.parts if hasattr(p, "text") and p.text
            )
            if text:
                author = getattr(event, "author", "system")
                events.append({
                    "author": author,
                    "content": text,
                    "invocation_id": event.invocation_id,
                })
                logger.info(f"[{author}] {text[:100]}...")

    return events
